### ISSUE TITLE
Update README 

### ISSUE THREAD

**Issue by omar-moreno** [JeffersonLab/hps-sim#22]
At the moment, the instructions are vague and difficult to follow.  Details instructions should be given that allows users to install hps-sim without having to search for instructions elsewhere.

**Comment by mholtrop** [comment]
I like the changes.

I would like to add that MacOS builds fine, once you have all the dependencies installed.

**Comment by omar-moreno** [comment]
Go for it.

I started adding documentation after running into installation issues last
night.  Figured I start documenting what works.

**Comment by JeremyMcCormick** [comment]
It has been well-updated.
