### ISSUE TITLE
Low level output from hps-sim does not agree with slic

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-sim#29]
We still see some differences between SLIC and hps-sim at the lowest level of the output.

**Comment by mholtrop** [comment]
Reopened issue9 - seems that the modification that were merged to master were overwritten again by a re-organization of the code, commit 69d4f4f.

**Comment by mholtrop** [comment]
After restoring the changes from Issue9:
There is still a significant difference between the way SLIC and hps-sim treat ECal hits. In SLIC, all the contribution from a single particle track are added together. In hps-sim they are kept separate. The result is that SLIC stores about 4 (max 40) hit contributions per hit per incident track, while hps-sim stores about 62 (max 3500) hit contributions. This is causing the next step in processing the hits to go a lot slower, and the file to be larger. It seems all these separate hit contributions are not needed. 
Below a graph of single electrons @ 2.3 GeV on the ECal, number of contributions per hit. Red is from SLIC, blue is from hps-sim.
![Hit contributions](https://user-images.githubusercontent.com/4603874/46087508-7cde9b80-c178-11e8-8ca9-827996b78afd.png)

It is not clear whether there is a processing issue with all these additional hit contributions in the hps-java code.

**Comment by mholtrop** [comment]
Set a  cut on processTrack()
` if ((regionInfo && regionInfo->getStoreSecondaries() && ( aTrack->GetKineticEnergy() > regionInfo->getThreshold())) || isPrimary) {`
Similar to the one used in SLIC. The result is fewer low energy MCParticles stored, but still not the same as the number stored by SLIC. This, strangely, did not affect the number of ECAL hit contributions.
[Number_of_MCparticles.pdf](https://github.com/JeffersonLab/hps-sim/files/2422274/Number_of_MCparticles.pdf)
![image](https://user-images.githubusercontent.com/4603874/46120450-b990ae00-c1dd-11e8-9e06-24c626aff7a3.png)

**Comment by mholtrop** [comment]
Overshoot. When cutting on the region threshold (set by LCDD) I get ***fewer*** particles than SLIC!
But the mechanism is now clear. Here the standard threshold is 1MeV. This is when, unlike above, the code actually obeys the energy cut set on particles, even if they create hits.

![image](https://user-images.githubusercontent.com/4603874/46165491-c6a1b180-c25e-11e8-9232-553b03cbc820.png)


The  number of contributions to a hit is now reduced to the number of MCParticles written.
![image](https://user-images.githubusercontent.com/4603874/46165432-9a863080-c25e-11e8-86fc-eca2523d5f10.png)

**Comment by JeremyMcCormick** [comment]
I have done work so that the collections are much closer now.  PR #49 adds several of these changes.

I think one last thing to try is adding the check from slic's TrackManager that makes sure the parents of a particle are saved.  This may also improve the agreement slightly.

**Comment by JeremyMcCormick** [comment]
I am going to close this generic issue out and open up more specific ones as branches based on this issue have been merged already.  (It is not totally resolved yet due to differences in the particle collections, and I will open a separate issue on that topic.)

**Comment by JeremyMcCormick** [comment]
I am going to close this generic issue out and open up more specific ones as branches based on this issue have been merged already.  (It is not totally resolved yet due to differences in the particle collections, and I will open a separate issue on that topic.)
