### ISSUE TITLE
Improve selection of which MCParticles to write out

### ISSUE THREAD

**Issue by mholtrop** [JeffersonLab/hps-sim#42]
Currently, too many MCParticles are written out for general use. See comments and graph in issue37. A better, more flexible method is needed to choose what is written out. 

Note: The writing of the ECal hit contributions is linked with this issue, since every ECal hit contribution saves the track that caused this contribution, and those tracks are then written out as MCParticles. 
There is probably  no real reason to save every hit contribution individually, but summing over them is currently handled by LCDD on a per track basis.

**Comment by JeremyMcCormick** [comment]
Closing as this issue is too generic (MCParticle output can be improved but need more specific requests)
