### ISSUE TITLE
Add event transform for lhe_tridents_displacetime

### ISSUE THREAD

**Issue by JeremyMcCormick** [JeffersonLab/hps-sim#8]
This script displaces the time and magically transmutes particles with PDG 611 and -611 to 11 and -11 (electrons and positrons, respectively).

No idea why the event generator uses these incorrect PDG IDs in the first place...

**Comment by omar-moreno** [comment]
611 is used to distinguish the e+e- that come from the A'.

**Comment by JeremyMcCormick** [comment]
Need to double check but this may already have been resolved.
